nationen_dict = { 
        "Afghanistan" : "004",
        "AFRIKA, nicht näher zuordenbar" : "999",
        "Ägypten" : "818",
        "Albanien" : "008",
        "Algerien" : "012",
        "Amerik. Jungferninseln" : "850",
        "Amerik. Samoa" : "999",
        "Amerikanische Jungferninseln" : "850",
        "Andorra" : "020",
        "Angola" : "024",
        "Anguilla" : "660",
        "Antarktis" : "010",
        "Antigua und Barbuda" : "028",
        "Äquatorialguinea" : "226",
        "Arabische Republik Ägypten" : "818",
        "Argentinien" : "032",
        "Armenien" : "051",
        "Aruba" : "533",
        "Aserbaidschan" : "031",
        "ASIEN, nicht näher zuordenbar" : "999",
        "Äthiopien" : "231",
        "Australien" : "036",
        "Bahamas" : "044",
        "Bahrein" : "048",
        "Bangladesch" : "050",
        "Bangladesh" : "050",
        "Barbados" : "052",
        "Belarus (Weißrußland)" : "112",
        "Belau (Palau-Inseln)" : "999",
        "Belgien" : "056",
        "Belize" : "084",
        "Benin" : "204",
        "Bermuda" : "060",
        "Bermuda-Inseln" : "060",
        "Bhutan" : "064",
        "Bolivien" : "068",
        "Bosnien-Herzegovina" : "070",
        "Bosnien-Herzegowina" : "070",
        "Botsuana" : "072",
        "Botswana" : "072",
        "Bouvetinsel" : "074",
        "Br.T/Ind.O" : "086",
        "Brasilien" : "076",
        "Britische  Jungferninseln" : "092",
        "Britische Jungferninseln" : "092",
        "Britisches Territorium im Ind. Ozean" : "086",
        "Brunei Darussalam" : "096",
        "Brunei" : "096",
        "Bulgarien" : "100",
        "Bundesrepublik Deutschland" : "276",
        "Burkina Faso" : "854",
        "Burundi" : "108",
        "Chile" : "152",
        "China" : "156",
        "Code d' Ivoire (Elfenbeink.)" : "384",
        "Cookinseln" : "184",
        "Costa Rica" : "188",
        "Cypern" : "196",
        "Dahome" : "204",
        "Dänemark" : "208",
        "Demokr. Volksrepublik Korea" : "408",
        "Demokratische Republik Kongo (Zaire)" : "180",
        "Deutschland (ehem. DDR)" : "999",
        "Deutschland" : "276",
        "Dominica" : "212",
        "Dominikanische Republik" : "214",
        "Dschibuti" : "262",
        "Ecuador" : "218",
        "ehem. Sowjetunion" : "999",
        "ehemalige Tschechoslowakei" : "999",
        "El Salvador" : "222",
        "Elfenbeinküste" : "384",
        "Eritrea" : "232",
        "Estland" : "233",
        "Falklandinseln (Malwinen)" : "238",
        "Falkland-Inseln (zu GB)" : "238",
        "Färöer Inseln" : "234",
        "Färöer" : "234",
        "Fidschi" : "242",
        "Finnland" : "246",
        "Fr.Südgeb." : "260",
        "Frankreich" : "250",
        "Franz. Polynesien" : "258",
        "Französisch Guyana" : "254",
        "Französische Süd- u. Antarktisgebiete" : "260",
        "Französisch-Guayana" : "254",
        "Französisch-Polynesien" : "258",
        "Gabun" : "266",
        "Gambia" : "270",
        "Georgien" : "268",
        "Ghana" : "288",
        "Gibraltar" : "292",
        "Grenada" : "308",
        "Griechenland" : "300",
        "Grönland (zu Dänemark)" : "304",
        "Grönland" : "304",
        "Großbritannien und Nordirland" : "826",
        "Großbritannien" : "826",
        "Guadeloupe (zu Frankreich)" : "312",
        "Guadeloupe" : "312",
        "Guam (zu USA)" : "316",
        "Guam" : "316",
        "Guatemala" : "320",
        "Guinea-Bissau" : "624",
        "Guyana" : "328",
        "Haiti" : "332",
        "Hawaii (zu USA)" : "840",
        "Heard und McDonaldinseln" : "334",
        "Heard/McDo" : "334",
        "Honduras" : "340",
        "Hongkong" : "344",
        "Indien" : "356",
        "Indonesien" : "360",
        "International" : "903",
        "Irak" : "368",
        "Iran" : "364",
        "Irland" : "372",
        "Island" : "352",
        "Israel" : "376",
        "Italien" : "380",
        "Jamaika" : "388",
        "Japan" : "392",
        "Jemen (ehem. demokr. VR)" : "999",
        "Jemen" : "887",
        "Jordanien" : "400",
        "Jugoslawien" : "890",
        "Kaimaninseln" : "136",
        "Kambodscha" : "116",
        "Kamerun" : "120",
        "Kanada" : "124",
        "Kap Verde" : "132",
        "Kasachstan" : "398",
        "Katar" : "634",
        "Kenia" : "404",
        "Kirgisistan" : "417",
        "Kiribati (Gilbert-Inseln)" : "296",
        "Kiribati" : "296",
        "Kleine Antillen" : "999",
        "Kokosinseln" : "166",
        "Kolumbien" : "170",
        "Komoren" : "174",
        "Kongo (Brazzaville)" : "178",
        "Konventionsfluechtling" : "999",
        "Kosovo" : "983",
        "Kroatien" : "191",
        "Kuba" : "192",
        "Kuwait" : "414",
        "Laos" : "418",
        "Lesotho" : "426",
        "Lettland" : "428",
        "Libanon" : "422",
        "Liberia" : "430",
        "Libyen" : "434",
        "Liechtenstein" : "438",
        "Litauen" : "440",
        "Luxemburg" : "442",
        "Macao (zu Volksrepublik China)" : "446",
        "Macao" : "446",
        "Madagaskar" : "450",
        "Malawi" : "454",
        "Malaysia" : "458",
        "Malediven" : "462",
        "Mali" : "466",
        "Malta" : "470",
        "Marianen (zu USA)" : "580",
        "Marokko" : "504",
        "Marschall-Inseln (zu USA)" : "584",
        "Marshallinseln" : "584",
        "Martinique (zu Frankreich)" : "474",
        "Martinique" : "474",
        "Mauretanien" : "478",
        "Mauritius" : "480",
        "Mayotte" : "175",
        "Mazedonien" : "807",
        "Mexico" : "484",
        "Mexiko" : "484",
        "Mikronesien - Föderierte Staaten von" : "583",
        "Mikronesien" : "583",
        "Moldau" : "498",
        "Monaco" : "492",
        "Mongolei" : "496",
        "Montenegro" : "499",
        "Montserrat" : "500",
        "Mosambik" : "508",
        "Myanmar" : "104",
        "Namibia" : "516",
        "Nauru" : "520",
        "Nepal" : "524",
        "NEU!!!" : "728",
        "Neukaledonien" : "540",
        "Neuseeland" : "554",
        "Nicaragua" : "558",
        "Niederlande" : "528",
        "Niederländische Antillen" : "530",
        "Niger" : "562",
        "Nigeria" : "566",
        "Niue" : "570",
        "Nordborneo" : "999",
        "Nördliche Marianen" : "580",
        "Norfolkinseln" : "574",
        "Norwegen" : "578",
        "Oman" : "512",
        "Österreich" : "040",
        "Ostimor" : "999",
        "Pakistan" : "586",
        "Palästina/Westjordanland-Gaza" : "275",
        "Palästinensische Gebiete - Besetzte" : "275",
        "Palau" : "585",
        "Panama" : "591",
        "Papua-Neuguinea" : "598",
        "Paraguay" : "600",
        "Peru" : "604",
        "Philippinen" : "608",
        "Pitcairn" : "612",
        "Pitcairninseln" : "612",
        "Polen" : "616",
        "Portugal" : "620",
        "Puerto Rico (zu USA)" : "630",
        "Puerto Rico" : "630",
        "Republik China (Taiwan)" : "158",
        "Republik Guinea" : "324",
        "Republik Kongo (Brazaville)" : "178",
        "Republik Korea (Südkorea)" : "408",
        "Republik Korea" : "410",
        "Republik Kosovo" : "983",
        "Reunion" : "638",
        "Ruanda" : "646",
        "Rumänien" : "642",
        "Russische Föderation" : "643",
        "Russland" : "643",
        "Rwanda" : "646",
        "Sahara (dzt. zu Marokko)" : "732",
        "Sahara, Demokr. Arab. Republik" : "732",
        "Salomonen" : "090",
        "Sambia" : "894",
        "Samoa" : "882",
        "San Marino" : "674",
        "Sao Tome and Principe" : "678",
        "Sao Tome und Principe" : "678",
        "Saudi Arabien" : "682",
        "Saudi-Arabien" : "682",
        "Schweden" : "752",
        "Schweiz" : "756",
        "Senegal" : "686",
        "Serbien und Montenegro" : "891",
        "Serbien" : "688",
        "Seychellen" : "690",
        "Sierra Leone" : "694",
        "Sikkim (zu Indien)" : "999",
        "Simbabwe" : "716",
        "Singapur" : "702",
        "Slowakei" : "703",
        "Slowenien" : "705",
        "Somalia" : "706",
        "Spanien" : "724",
        "Sri Lanka" : "144",
        "St. Helena, Ascension & Tristan da Cunha" : "654",
        "St. Kittes und Nevis" : "659",
        "St. Kitts und Nevis" : "659",
        "St. Lucia" : "662",
        "St. Pierre und Miquelon" : "666",
        "St. Vincent und die Grenadinen" : "670",
        "St. Vincent und Grenadines" : "670",
        "St.Helena" : "654",
        "St.Pierre" : "666",
        "Staatenlos" : "999",
        "Staatenlos-Nationalität ungeklärt" : "999",
        "Staatsbürgerschaft unbekannt" : "999",
        "Südafrika mit SW-Afrika" : "710",
        "Südafrika" : "710",
        "Sudan" : "729",
        "Südgeorgien u. d. Südl. Sandwichinseln" : "239",
        "Süd-Georgien" : "239",
        "Süd-Sandwich-Inseln" : "239",
        "Südsudan" : "728",
        "Surinam" : "740",
        "Suriname (zu Niederlande)" : "740",
        "Svalbard und Jan Mayen" : "744",
        "Svalbard" : "744",
        "Swasiland" : "748",
        "Syrien" : "760",
        "Tadschikistan" : "762",
        "Tadschikstan" : "762",
        "Taiwan" : "158",
        "Tansania" : "834",
        "Thailand" : "764",
        "Timor (zu Indonesien)" : "999",
        "Timor-Leste" : "626",
        "Togo" : "768",
        "Tokelau" : "772",
        "Tonga" : "776",
        "Trinidad und Tobago" : "780",
        "Tschad" : "148",
        "Tschechien" : "203",
        "Tschechische Republik" : "203",
        "Tunesien" : "788",
        "Türkei" : "792",
        "Turkmenistan" : "795",
        "Turks- und Caicosinseln" : "796",
        "Turks/Caic" : "796",
        "Tuvalu (Ellice-Inseln)" : "798",
        "Tuvalu" : "798",
        "Uganda" : "800",
        "Ukraine" : "804",
        "Ungarn" : "348",
        "Uruguay" : "858",
        "Usbekistan" : "860",
        "Vanuatu (neue Hebriden)" : "548",
        "Vanuatu" : "548",
        "Vatikan" : "336",
        "Vatikanstaat" : "336",
        "Venezuela" : "862",
        "Vereinigte Arabische Emirate" : "784",
        "Vereinigte Staaten (USA)" : "840",
        "Vereinigte Staaten von Amerika" : "840",
        "Vietnam" : "704",
        "Volksrepublik China" : "156",
        "Volksrepublik Korea (Nordkorea)" : "410",
        "Wallis und Futuna Inseln" : "876",
        "Wallis und Futuna" : "876",
        "Weihnachtsinsel" : "162",
        "Weihnachtsinseln" : "162",
        "Weißrussland" : "112",
        "Westindische assoz. Staaten" : "999",
        "Westsahara" : "732",
        "Westsamoa" : "882",
        "West-Samoa" : "999",
        "Zaire (Kinshasa)" : "180",
        "Zentralafrikanische Republik" : "140",
        "Zypern" : "196"}